# Generated by Django 4.1.4 on 2023-01-06 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
