# Generated by Django 4.1.4 on 2023-02-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activate_key',
            field=models.CharField(default='3333', max_length=255),
        ),
    ]
