# Generated by Django 4.1.4 on 2023-02-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_user_activate_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isEmailConfimed',
            field=models.BooleanField(default=False),
        ),
    ]
