# Generated by Django 4.1.4 on 2023-02-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_user_isemailconfimed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='activate_key',
            new_name='activate_key_email',
        ),
        migrations.AddField(
            model_name='user',
            name='activate_key_username',
            field=models.CharField(default='fr', max_length=500),
        ),
    ]
