# Generated by Django 4.1.4 on 2023-02-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_rename_activate_key_user_activate_key_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activate_key_username',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
