# Generated by Django 4.1.4 on 2023-02-10 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_alter_user_activate_key_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isEmailConfimed',
            new_name='isEmailConfirmed',
        ),
    ]
