# Generated by Django 4.1.4 on 2023-02-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='count_following',
            field=models.IntegerField(default=0),
        ),
    ]
