# Generated by Django 4.1.4 on 2022-12-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='publication',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.IntegerField(default=11),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
