# Generated by Django 4.1.4 on 2023-01-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pic',
            new_name='image',
        ),
    ]
