# Generated by Django 4.1.4 on 2023-01-05 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_like_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 5, 10, 1, 12, 922760, tzinfo=datetime.timezone.utc)),
        ),
    ]
