export const apiEndpoints = {
    login: 'token/',
    register: 'register/',
    refreshToken: 'token/refresh/',
    posts: 'posts/',
    post: 'post/',
    comment: 'comment/',
    logout: 'logout/',
    user: 'user/',
    editProfile: 'edit-profile/',
    userInfo: 'user-info/',
    changePassword: 'password/change/',
    restorePassword: 'password-reset/',
    restorePasswordConfirm: 'password-reset/confirm/',
    confirmEmail: 'email-confirm/',
    sendConfirmEmail: 'email-confirm/send/',

    getAllNotifications: 'notifications/all/',
    getLastNotifications: 'notifications/last/',
    connectToNotification: 'notifications/connect/',
    readNotification: (id: string) => `notification/${id}/`,
    readAllNotification: 'notifications/read-all/',
};
