export const enum Paths {
    WELCOME = '',
    MAIN = 'main',
    LOGIN = 'login',
    REGISTER = 'register',
    POST = 'post',
    USER = 'user',
    CHANGE_PASSWORD = 'change-password',
    RESTORE_PASSWORD = 'restore-password',
    RESTORE_PASSWORD_CONFIRM = 'restore-password/confirm',
    CONFIRM_EMAIL = 'confirm-email',
    CREATE_POST = 'create-post',
    TAG = `main`,
    EDIT_PROFILE = 'edit-profile',
    EDIT_POST = 'edit-post',
}

export const enum PathsToNavigate {
    WELCOME = '/',
    MAIN = '/main',
    LOGIN = '/login',
    REGISTER = '/register',
    POST = '/post',
    USER = '/user',
    CHANGE_PASSWORD = '/change-password',
    RESTORE_PASSWORD = '/restore-password',
    RESTORE_PASSWORD_CONFIRM = '/restore-password/confirm',
    CONFIRM_EMAIL = '/confirm-email',
    CREATE_POST = '/create-post',
    TAG = '/main',
    EDIT_PROFILE = '/edit-profile',
    EDIT_POST = '/edit-post',
}
