export { default as MainPage } from './MainPage/MainPage';
export { default as LoginPage } from './LoginPage/LoginPage';
export { default as RegisterPage } from './RegisterPage/RegisterPage';
export { default as ChangePasswordPage } from './ChangePasswordPage/ChangePasswordPage';
export { default as RestorePasswordPage } from './RestorePasswordPage/RestorePasswordPage';
export { default as PostPage } from './PostPage/PostPage';
export { default as WelcomePage } from './WelcomePage/WelcomePage';
export { default as PageNotFound } from './PageNotFound/PageNotFound';
export { default as CreatePostPage } from './CreatePostPage/CreatePostPage';
